# Generated by Django 3.0.5 on 2020-04-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('X_Ray_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xray',
            name='birthdate',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='xray',
            name='comment',
            field=models.TextField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name='xray',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='xray',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='xray_images/'),
        ),
    ]
