# Generated by Django 3.0.5 on 2020-04-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('X_Ray_App', '0003_auto_20200413_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xray',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='xray',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='xray',
            name='name',
        ),
        migrations.AlterField(
            model_name='xray',
            name='image',
            field=models.ImageField(default=None, upload_to='x_ray_images'),
        ),
    ]
